spring:
  datasource:
    url: jdbc:mysql://192.168.1.81:3306/gvtsasTest?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: tester
    password: 123456




